### ISSUE TITLE
Vdem doesn't include year 2023, despite shown on OWID

### ISSUE THREAD

**Issue by CosmicOutlaw** [owid/notebooks#9]
Unless I am missing something, the 'Download this data' link [here](https://ourworldindata.org/explorers/democracy?time=1989..latest&showSelectionOnlyInTable=1&Dataset=Varieties+of+Democracy&Metric=Varieties+of+democracy&Sub-metric=Main+indices&country=~USA) leads to this repo. When navigating for V-Dem data, in the [final](https://github.com/owid/notebooks/tree/main/BastianHerre/democracy/datasets/final) structure, the data sets only include data up to 2022 despite the visualization on OWID displaying 2023 values. Why?

**Comment by bastianherre** [comment]
Thanks for reaching out! We recently updated the democracy data on the website to include 2023 but didn't update the GitHub repository because it was part of the previous less efficient data pipeline, and are about to delete the repository entirely.

What you can do instead is download the data for any chart by clicking on the "Download" button [in the lower right-hand corner](https://ourworldindata.org/explorers/democracy?time=1989..latest&showSelectionOnlyInTable=1&Dataset=Varieties+of+Democracy&Metric=Varieties+of+democracy&Sub-metric=Main+indices&country=~USA). Would that also work for you?
